apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvel
  labels:
    app: marvel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marvel
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: marvel
    spec:
      restartPolicy: Always
      containers:
      - image: us-central1-docker.pkg.dev/gcp-vpn-428200/prueba-gaby/imagen:latest
        name: marvel