apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: marvel-prod
  labels: {}
requireApproval: true
gke:
  location: projects/gcp-vpn-428200/locations/us-central1-c/clusters/cluster-1